// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHLaE0c_Eppw0-kf7a0iiHd3vON9uFbzY',
    appId: '1:357631715133:web:34c0e36c04930eebb68754',
    messagingSenderId: '357631715133',
    projectId: 'fyp-project-fb9c6',
    authDomain: 'fyp-project-fb9c6.firebaseapp.com',
    storageBucket: 'fyp-project-fb9c6.firebasestorage.app',
    measurementId: 'G-Z8VRY49FLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHroFitCUwKAH33-PizcpqeTik0lQ-40k',
    appId: '1:357631715133:android:0b3aff8eee9d24c2b68754',
    messagingSenderId: '357631715133',
    projectId: 'fyp-project-fb9c6',
    storageBucket: 'fyp-project-fb9c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDEOa9P-i_TiAJDQWUwnGtQOlw11bxRB4',
    appId: '1:357631715133:ios:1133737b2143941ab68754',
    messagingSenderId: '357631715133',
    projectId: 'fyp-project-fb9c6',
    storageBucket: 'fyp-project-fb9c6.firebasestorage.app',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDEOa9P-i_TiAJDQWUwnGtQOlw11bxRB4',
    appId: '1:357631715133:ios:1133737b2143941ab68754',
    messagingSenderId: '357631715133',
    projectId: 'fyp-project-fb9c6',
    storageBucket: 'fyp-project-fb9c6.firebasestorage.app',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHLaE0c_Eppw0-kf7a0iiHd3vON9uFbzY',
    appId: '1:357631715133:web:c6f3bddf88cf74d7b68754',
    messagingSenderId: '357631715133',
    projectId: 'fyp-project-fb9c6',
    authDomain: 'fyp-project-fb9c6.firebaseapp.com',
    storageBucket: 'fyp-project-fb9c6.firebasestorage.app',
    measurementId: 'G-5H8M6BZ5LY',
  );
}
